# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee53b0b24bcd97eb40b728a28a4c5edfc80e186129c0a8b1e8c857b98f0cf83d01bc009f9312c1aefcdeeb735fee7db6ccb69e99a522f3f9a416bfdd94b6912

test:
  secret_key_base: 72970c6674b7227d81f1eda26375e21264e155123a705143046bacb70ba6e224d29a0bcc6712eaa5a9e183e132f9408762577afc221022a71fd69f9265884205

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
